DROP TABLE IF EXISTS user_game_relationships CASCADE
CREATE TABLE user_game_relationships (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id REFERENECES users(id) ON DELETE CASCADE,
  game_id REFERENECES games(id) ON DELETE CASCADE,
  liked BOOLEAN NOT NULL DEFAULT FALSE,
  played BOOLEAN NOT NULL DEFAULT FALSE,
  play_list BOOLEAN NOT NULL DEFAULT FALSE,
);